name: 戦型・戦法
description: 戦型や戦法のwiki作成用
title: "[戦型・戦法名]"
body:
- type: markdown
  attributes:
    value: '戦型や戦法のwiki作成します。'

- type: input
  id: part_name
  attributes:
    label: 部品名
  validations:
    required: false
    
- type: dropdown
  id: usage_record
  attributes:
    label: 特定型
    options:
    - なし
    - 居飛車
    - 振り飛車
    - 角交換
    - 角交換拒否
    default: 0
  validations:
    required: false
    
- type: textarea
  id: notes
  attributes:
    value: |
      |９ 　|８ 　|７ 　|６ 　|５ 　|４ 　|３ 　|２ 　|１ 　|／ 　|
      |-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
      |香 ▽|桂 ▽|銀 ▽|金 ▽|玉 ▽|金 ▽|銀 ▽|桂 ▽|香 ▽|一 　|
      |　 　|飛 ▽|　 　|　 　|　 　|　 　|　 　|角 ▽|　 　|二 　|
      |歩 ▽|歩 ▽|歩 ▽|歩 ▽|歩 ▽|歩 ▽|歩 ▽|歩 ▽|歩 ▽|三 　|
      |　 　|　 　|　 　|　 　|　 　|　 　|　 　|　 　|　 　|四 　|
      |　 　|　 　|　 　|　 　|　 　|　 　|　 　|　 　|　 　|五 　|
      |　 　|　 　|　 　|　 　|　 　|　 　|　 　|　 　|　 　|六 　|
      |　▲歩|　▲歩|　▲歩|　▲歩|　▲歩|　▲歩|　▲歩|　▲歩|　▲歩|七 　|
      |　 　|　▲角|　 　|　 　|　 　|　 　|　 　|　▲飛|　 　|八 　|
      |　▲香|　▲桂|　▲銀|　▲金|　▲王|　▲金|　▲銀|　▲桂|　▲香|九 　|
  validations:
    required: false
